version: 0.2

phases:
  install:
    commands:
      - set -e
      - DEFAULT_PATH=$(pwd)
      - TF_DISTRIBUTION="oss"
      - TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
      - TF_VERSION="0.15.5"
      - AWS_MODULE_GIT_REF="main"  # Update this with your branch name
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone --quiet -b $AWS_MODULE_GIT_REF https://github.com/ronilp1/test.git manualtrigger
      - chmod +x $DEFAULT_PATH/manualtrigger/sources/scripts/creds.sh
      - TARGET_ACCOUNT_IDS=$(echo $TARGET_ACCOUNT_IDS | tr "," "\n")
      - for ACCOUNT_ID in $TARGET_ACCOUNT_IDS; do $DEFAULT_PATH/manualtrigger/sources/scripts/creds.sh $ACCOUNT_ID; done
      - python3 -m venv $DEFAULT_PATH/aft-venv
      - $DEFAULT_PATH/aft-venv/bin/pip install pip==22.1.2
      - $DEFAULT_PATH/aft-venv/bin/pip install jinja2-cli==0.7.0 Jinja2==3.0.1 MarkupSafe==2.0.1 boto3==1.18.56 requests==2.26.0
      - python3 -m venv $DEFAULT_PATH/api-helpers-venv
      - $DEFAULT_PATH/api-helpers-venv/bin/pip install -r $DEFAULT_PATH/manualtrigger/sources/aft-customizations-repos/aft-global-customizations/api_helpers/requirements.txt

  pre_build:
    on-failure: ABORT
    commands:
      - source $DEFAULT_PATH/api-helpers-venv/bin/activate
      - for ACCOUNT_ID in $TARGET_ACCOUNT_IDS; do export AWS_PROFILE="codebuild-target-${ACCOUNT_ID}"; done

  build:
    on-failure: CONTINUE
    commands:
      - echo "Installing Terraform"
      - curl -q -o terraform_${TF_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - mkdir -p /opt/aft/bin
      - unzip -q -o terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /opt/aft/bin
      - chmod +x /opt/aft/bin/terraform
      - /opt/aft/bin/terraform -no-color --version
      - cd $DEFAULT_PATH/manualtrigger/sources/aft-customizations-repos/aft-global-customizations/terraform
      - for ACCOUNT_ID in $TARGET_ACCOUNT_IDS; do export AWS_PROFILE="codebuild-target-${ACCOUNT_ID}"; /opt/aft/bin/terraform init -no-color; /opt/aft/bin/terraform apply -no-color --auto-approve; done
